% MATCHING PARAMETERS AUTO-GENERATED BY MATHEMATICA 
function [lb, ub, maxStepShots, maxShots, funEvals, funTol, xTol] = matchingParams()
	lb = [0,(-330),0];
	ub = [330,330,4];
	maxStepShots = 10;
	maxShots = 50;
	funEvals = 10000;
	funTol = (1/10000000000);
	xTol = (1/10000000000);
end
